apiVersion: v1
kind: Service
metadata:
  name: npestate-service
spec:
  selector:
    app: npestate
  ports:
    - protocol: TCP
      port: 80          # Port exposed by the Service
      targetPort: 3000   # Port inside the container where Next.js is running
  type: NodePort  # Optional, depending on your setup

