apiVersion: v1
kind: Service
metadata:
  name: npestate-service
spec:
  selector:
    app: npestate
  ports:
    - protocol: TCP
      port: 80          # Port exposed by the Service
      targetPort: 3000   # Port inside the container where Next.js is running
      nodePort: 31000    # Port on each node where the service will be exposed
  type: NodePort  # Exposes the service externally using a NodePort

